# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from acsilo_grpc import (
    aggregation_server_pb2 as acsilo__grpc_dot_aggregation__server__pb2,
)


class gRPCCommManagerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.sendMessage = channel.unary_unary(
            "/gRPCCommManager/sendMessage",
            request_serializer=acsilo__grpc_dot_aggregation__server__pb2.CommRequest.SerializeToString,
            response_deserializer=acsilo__grpc_dot_aggregation__server__pb2.CommResponse.FromString,
        )
        self.handleReceiveMessage = channel.unary_unary(
            "/gRPCCommManager/handleReceiveMessage",
            request_serializer=acsilo__grpc_dot_aggregation__server__pb2.CommRequest.SerializeToString,
            response_deserializer=acsilo__grpc_dot_aggregation__server__pb2.CommResponse.FromString,
        )


class gRPCCommManagerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def sendMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def handleReceiveMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_gRPCCommManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "sendMessage": grpc.unary_unary_rpc_method_handler(
            servicer.sendMessage,
            request_deserializer=acsilo__grpc_dot_aggregation__server__pb2.CommRequest.FromString,
            response_serializer=acsilo__grpc_dot_aggregation__server__pb2.CommResponse.SerializeToString,
        ),
        "handleReceiveMessage": grpc.unary_unary_rpc_method_handler(
            servicer.handleReceiveMessage,
            request_deserializer=acsilo__grpc_dot_aggregation__server__pb2.CommRequest.FromString,
            response_serializer=acsilo__grpc_dot_aggregation__server__pb2.CommResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "gRPCCommManager", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class gRPCCommManager(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def sendMessage(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/gRPCCommManager/sendMessage",
            acsilo__grpc_dot_aggregation__server__pb2.CommRequest.SerializeToString,
            acsilo__grpc_dot_aggregation__server__pb2.CommResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def handleReceiveMessage(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/gRPCCommManager/handleReceiveMessage",
            acsilo__grpc_dot_aggregation__server__pb2.CommRequest.SerializeToString,
            acsilo__grpc_dot_aggregation__server__pb2.CommResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
