# Method names

# no dp
METHOD_DEFAULT = "DEFAULT"
# silo-level DP-FedAVG https://arxiv.org/abs/1710.06963
METHOD_SILO_LEVEL_DP = "SILO-LEVEL-DP"
# a.k.a silo-specific sample-level DP https://arxiv.org/abs/2206.07902
METHOD_RECORD_LEVEL_DP = "RECORD-LEVEL-DP"
# group-DP based solution with group size k
METHOD_ULDP_GROUP = "ULDP-GROUP"
# with maximum number of records per user as a group size
METHOD_ULDP_GROUP_MAX = "ULDP-GROUP-max"
# with median number of records per user as a group size
METHOD_ULDP_GROUP_MEDIAN = "ULDP-GROUP-median"
# naive solution based on DP-FedAVG with larger noise
METHOD_ULDP_NAIVE = "ULDP-NAIVE"
METHOD_ULDP_SGD = "ULDP-SGD"
METHOD_ULDP_SGD_W = "ULDP-SGD-w"
METHOD_ULDP_SGD_S = "ULDP-SGD-s"
METHOD_ULDP_SGD_WS = "ULDP-SGD-ws"
METHOD_ULDP_AVG = "ULDP-AVG"
METHOD_ULDP_AVG_W = "ULDP-AVG-w"
METHOD_ULDP_AVG_S = "ULDP-AVG-s"
METHOD_ULDP_AVG_WS = "ULDP-AVG-ws"

# personalized versions
METHOD_PULDP_AVG = "PULDP-AVG"
METHOD_PULDP_AVG_ONLINE = "PULDP-AVG-online"
METHOD_PULDP_AVG_ONLINE_TRAIN = "PULDP-AVG-online-TRAIN"


METHOD_GROUP_NEED_USER_RECORD = {
    METHOD_ULDP_GROUP,
    METHOD_ULDP_GROUP_MAX,
    METHOD_ULDP_GROUP_MEDIAN,
    METHOD_ULDP_SGD,
    METHOD_ULDP_SGD_W,
    METHOD_ULDP_SGD_S,
    METHOD_ULDP_SGD_WS,
    METHOD_ULDP_AVG,
    METHOD_ULDP_AVG_W,
    METHOD_ULDP_AVG_S,
    METHOD_ULDP_AVG_WS,
    METHOD_PULDP_AVG,
    METHOD_PULDP_AVG_ONLINE,
}

METHOD_GROUP_ULDP_GROUPS = {
    METHOD_ULDP_GROUP,
    METHOD_ULDP_GROUP_MAX,
    METHOD_ULDP_GROUP_MEDIAN,
}

METHOD_GROUP_NO_SAMPLING = {
    METHOD_ULDP_SGD,
    METHOD_ULDP_SGD_W,
    METHOD_ULDP_AVG,
    METHOD_ULDP_AVG_W,
}

METHOD_GROUP_SAMPLING = {
    METHOD_ULDP_SGD_S,
    METHOD_ULDP_SGD_WS,
    METHOD_ULDP_AVG_S,
    METHOD_ULDP_AVG_WS,
    METHOD_PULDP_AVG,
}

METHOD_GROUP_NO_WEIGHTS = {
    METHOD_ULDP_SGD,
    METHOD_ULDP_SGD_S,
    METHOD_ULDP_AVG,
    METHOD_ULDP_AVG_S,
}

METHOD_GROUP_WEIGHTS = {
    METHOD_ULDP_SGD_W,
    METHOD_ULDP_AVG_W,
    METHOD_ULDP_SGD_WS,
    METHOD_ULDP_AVG_WS,
    METHOD_PULDP_AVG,
    METHOD_PULDP_AVG_ONLINE,
}

METHOD_GROUP_AGGREGATOR_PRIVACY_ACCOUNTING = {
    METHOD_SILO_LEVEL_DP,
    METHOD_ULDP_NAIVE,
    METHOD_ULDP_SGD,
    METHOD_ULDP_SGD_W,
    METHOD_ULDP_SGD_S,
    METHOD_ULDP_SGD_WS,
    METHOD_ULDP_AVG,
    METHOD_ULDP_AVG_W,
    METHOD_ULDP_AVG_S,
    METHOD_ULDP_AVG_WS,
    METHOD_PULDP_AVG,
    METHOD_PULDP_AVG_ONLINE,
}

METHOD_GROUP_DP = {
    METHOD_RECORD_LEVEL_DP,
    METHOD_ULDP_GROUP,
    METHOD_ULDP_GROUP_MAX,
    METHOD_ULDP_GROUP_MEDIAN,
    METHOD_SILO_LEVEL_DP,
    METHOD_ULDP_NAIVE,
    METHOD_ULDP_SGD,
    METHOD_ULDP_SGD_W,
    METHOD_ULDP_SGD_S,
    METHOD_ULDP_SGD_WS,
    METHOD_ULDP_AVG,
    METHOD_ULDP_AVG_W,
    METHOD_ULDP_AVG_S,
    METHOD_ULDP_AVG_WS,
    METHOD_PULDP_AVG,
    METHOD_PULDP_AVG_ONLINE,
}

METHOD_NO_DP_ACCOUNTING = {
    METHOD_DEFAULT,
    METHOD_PULDP_AVG,
    METHOD_PULDP_AVG_ONLINE,
}

METHOD_GROUP_GRADIENT = {
    METHOD_ULDP_SGD,
    METHOD_ULDP_SGD_W,
    METHOD_ULDP_SGD_S,
    METHOD_ULDP_SGD_WS,
}

METHOD_GROUP_AVG = {
    METHOD_ULDP_AVG,
    METHOD_ULDP_AVG_W,
    METHOD_ULDP_AVG_S,
    METHOD_ULDP_AVG_WS,
}

METHOD_GROUP_PARAMETER_DIFF = {
    METHOD_DEFAULT,
    METHOD_RECORD_LEVEL_DP,
    METHOD_ULDP_GROUP,
    METHOD_ULDP_GROUP_MAX,
    METHOD_ULDP_GROUP_MEDIAN,
    METHOD_ULDP_NAIVE,
    METHOD_ULDP_AVG,
    METHOD_ULDP_AVG_W,
}

METHOD_GROUP_USER_LEVEL_DATA_LOADER = {
    METHOD_ULDP_SGD,
    METHOD_ULDP_SGD_W,
    METHOD_ULDP_SGD_S,
    METHOD_ULDP_SGD_WS,
    METHOD_ULDP_AVG,
    METHOD_ULDP_AVG_W,
    METHOD_ULDP_AVG_S,
    METHOD_ULDP_AVG_WS,
    METHOD_PULDP_AVG,
    METHOD_PULDP_AVG_ONLINE,
}

METHOD_GROUP_SECURE_WEIGHTING = {
    METHOD_ULDP_SGD_W,
    METHOD_ULDP_SGD_WS,
    METHOD_ULDP_AVG_W,
    METHOD_ULDP_AVG_WS,
}
