name: Pants
run-name: test-workflow
on:
  workflow_dispatch:
    inputs:
      s3_artifact_id:
        description: 'Artifact identifier in S3'
        required: true
        default: 'cannibalization-data/hoge.pickle'
      environment:
        type: choice
        options:
          - dev
          - prod
concurrency:
  group: ${{ github.workflow }}-${{ inputs.environment }}
  cancel-in-progress: true
env:
  AWS_REGION: ap-northeast-1 
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - uses: iterative/setup-cml@v2

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo 'export PATH="$HOME/.local/bin:$PATH"' >> $GITHUB_ENV
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          poetry install

      - name: Run validation
        run: | 
            poetry run python \
            src/validate_test.py \
            --artifact_source ${{ github.event.inputs.s3_artifact_id }} \
            --artifact_path temp-artifact.pickle \
            --variables_file variables.txt \
            --stage ${{ inputs.environment }}

      - name: Read variables from file
        id: read_vars
        run: |
          source variables.txt
          echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV
          echo "LOCAL_ARTIFACT_PATH=$LOCAL_ARTIFACT_PATH" >> $GITHUB_ENV
          echo "LOCAL_ARTIFACT_META_DATA_PATH=$LOCAL_ARTIFACT_META_DATA_PATH" >> $GITHUB_ENV

      - name: Commit and push model file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cml pr create \
            ${{ env.LOCAL_ARTIFACT_PATH }} ${{ env.LOCAL_ARTIFACT_META_DATA_PATH }} \
            --title "Model Validation Report ${{ env.TIMESTAMP }}" \
            --body "$(cat report.md)"
            --branch "cannibalization-model-manual-update-${{ env.TIMESTAMP }}"